spring.application.name=Spring-Auth-server-Oauth2


spring.datasource.url=jdbc:mysql://localhost:3306/oauth2_auth_server
spring.datasource.username=nidhi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true